### PR TITLE
modified hello.c from Ishan's machine

### PR DESCRIPTION
**Pull request by Incognito5655**
I modified hello.c message from "Hello" to "Hello Dom".
Hope you like it.

### CODE REVIEW

**Comment by akshatpanda** [comment]
> I modified hello.c message from "Hello" to "Hello Dom".
> Hope you like it.

We have a merge conflict, but I will look into it and notify you soon.

**Comment by akshatpanda** [comment]
I  feel like house is much better because it references House M.D.
What do you think?

**Comment by Incognito5655** [comment]
That's rich.
But  I was going for the more badass Russian accent if you catch my drift.

**Comment by akshatpanda** [comment]
But we already have Russian badassery by "privyet.c" don't you think.
I think a badass, savage diagnostician reference will really make the project much better

**Comment by Incognito5655** [comment]
On a second though, I think you are right. Let's take my part out.

**Comment by akshatpanda** [comment]
I am glad we agreed upon a solution.

**Pull request closed without merging**
